GET http://localhost:5000/playlist

###
GET http://localhost:5000/playlist/1

###
GET http://localhost:5000/playlist/mostplayed

###
POST  http://localhost:5000/playlist/add
Content-Type: application/json

{
    "title": "Lethocerus deyrollei",
    "artist": ["Aimer"],
    "url": "https://open.spotify.com/track/2HovXsvcdJur52BOcYGydz?si=d76d4b5706234600"
}


###
PATCH  http://localhost:5000/playlist/update/1
Content-Type: application/json

{
    "title": "Lethocerus deyrollei",
    "artist": ["Aimer"],
    "url": "https://open.spotify.com/track/2HovXsvcdJur52BOcYGydz?si=d76d4b5706234600"
}


###
DELETE http://localhost:5000/playlist/delete/1


